# Pre-defined lists for composite phrase generation
# Each response is built from: PREFIX + CORE + SUFFIX

# YES response parts
YES_PREFIXES = [
    "Oh yeah,",
    "Listen,",
    "Honestly,",
    "Look,",
    "Trust me,",
    "Well,",
    "Alright,",
    "You know what,",
    "Hell yeah,",
    "Okay,",
    "By all means,",
    "No doubt,",
    "Yup,",
    "Most definitely,",
    "For sure,",
    "Absolutely,",
    "Guess what,",
    "Rest assured,",
    "You'd better believe it,",
    "Without hesitation,",
    "",  # empty string for no prefix
]

YES_CORES = [
    "you should do it",
    "go for it",
    "it's a great idea",
    "that's the right move",
    "this is your moment",
    "make it happen",
    "seize the opportunity",
    "don't hesitate",
    "that's a yes from me",
    "full steam ahead",
    "green light on this one",
    "I'm giving you the thumbs up",
    "you've got my blessing",
    "absolutely yes",
    "no reason not to",
    "you've got nothing to lose",
    "now's your chance",
    "all signs point to yes",
    "I'd say do it",
    "totally worth it",
    "it's written in the stars",
    "can't see a reason against it",
    "my answer is yes",
    "bet on it",
    "I'm confident you should",
]

YES_SUFFIXES = [
    ", without a doubt!",
    ", for sure!",
    " 100%!",
    ", no questions asked!",
    ", trust yourself!",
    ", you got this!",
    ", no regrets!",
    ", all the way!",
    ", why not?",
    ", definitely!",
    ", !",
    ", don't even think twice!",
    ", let nothing stop you!",
    ", get going!",
    ", make it count!",
    ", this is the green light!",
    ", without looking back!",
    ", as soon as possible!",
    ", it’s your time!",
    ", let’s do this!",
]

# NO response parts
NO_PREFIXES = [
    "Sorry,",
    "Look,",
    "Honestly,",
    "Listen,",
    "Nah,",
    "Well,",
    "To be frank,",
    "Not gonna lie,",
    "I hate to say it,",
    "Hmm,",
    "Regretfully,",
    "No way,",
    "I must say,",
    "With respect,",
    "Even though it's tough,",
    "Unfortunately,",
    "I'm afraid,",
    "Let me be clear,",
    "If I'm honest,",
    "",  # empty string for no prefix
]

NO_CORES = [
    "I don't think so",
    "that's not the move",
    "better skip this one",
    "not your best idea",
    "hold off on that",
    "reconsider this",
    "think twice about it",
    "probably not",
    "that's a no from me",
    "don't do it",
    "step back from this",
    "maybe another time",
    "red flag on this one",
    "abort mission",
    "I'd pass on this",
    "now might not be the time",
    "doesn't look good",
    "it's a thumbs down",
    "I'd avoid it",
    "not advisable right now",
    "danger zone here",
    "save it for later",
    "not today",
    "I'd think again",
    "I wouldn't recommend it",
]

NO_SUFFIXES = [
    ", just saying.",
    " my friend.",
    " to be honest.",
    ", trust me on this.",
    ", not today.",
    ", sorry.",
    ", no way.",
    ", hard pass.",
    ", not recommended.",
    ", believe me.",
    ".",
    ", that's my two cents.",
    ", better safe than sorry.",
    ", it’s not worth the risk.",
    ", heed my advice.",
    ", trust your gut on this one.",
    ", better luck next time.",
    ", and that's final.",
    ", for your own good.",
    ", I mean it.",
]